# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ['1.21'] # 注意：目前Go 1.23还未发布，使用最新的稳定版1.21

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      working-directory: ./go
      run: |
        go build -o ../dist/app.exe -v ./...
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./go
      run: |
        go build -o ../dist/app -v ./...
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Test
      working-directory: ./go
      run: go test -v ./...

    - name: Upload Windows Build
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/app.exe
        retention-days: 5

    - name: Upload Linux Build
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: dist/app
        retention-days: 5
