name: GraalVM Native Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean package assembly:single --file pom.xml

    - name: Prepare for Native Image
      run: |
        mkdir -p target/native-image
        cp target/Copilot2API-*-jar-with-dependencies.jar target/native-image/Copilot2API.jar

    - name: Build Native Image
      run: |
        cd target/native-image
        native-image \
          -H:+AddAllCharsets \
          -jar Copilot2API.jar \
          --enable-https \
          --enable-http \
          --static \
          --no-fallback \
          --initialize-at-build-time=Main \
          --initialize-at-build-time=CompletionHandler \
          --initialize-at-build-time=EmbeddingHandler \
          --initialize-at-build-time=HeadersInfo \
          --initialize-at-build-time=TokenManager \
          --initialize-at-build-time=utils

    - name: Upload Native Image
      uses: actions/upload-artifact@v4
      with:
        name: copilot-api-native
        path: target/native-image/copilot2api
        retention-days: 5

    # 创建 Release（当推送标签时）
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/native-image/copilot2api
          target/Copilot2API-*-jar-with-dependencies.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
