name: GraalVM Native Image Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'go/**'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'go/**'
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean package assembly:single --file pom.xml

    - name: Rename JAR file
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p dist
        cp target/*-jar-with-dependencies.jar dist/Copilot-api.jar

    - name: Upload JAR
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: jar-build
        path: dist/Copilot-api.jar
        retention-days: 5

    - name: Prepare for Native Image
      shell: bash
      run: |
        mkdir -p target/native-image
        cp dist/Copilot-api.jar target/native-image/

    - name: Build Native Image (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd target/native-image
        native-image \
          -H:+AddAllCharsets \
          -jar Copilot-api.jar \
          -H:Name=Copilot-api \
          --enable-https \
          --enable-http \
          --static \
          --no-fallback \
          --initialize-at-build-time=Main \
          --initialize-at-build-time=CompletionHandler \
          --initialize-at-build-time=EmbeddingHandler \
          --initialize-at-build-time=HeadersInfo 

    - name: Build Native Image (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        cd target\native-image
        native-image ^
          -H:+AddAllCharsets ^
          -jar Copilot-api.jar ^
          -H:Name=Copilot-api ^
          --enable-https ^
          --enable-http ^
          --static ^
          --no-fallback ^
          --initialize-at-build-time=Main ^
          --initialize-at-build-time=CompletionHandler ^
          --initialize-at-build-time=EmbeddingHandler ^
          --initialize-at-build-time=HeadersInfo 

    - name: Upload Windows Build
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: target/native-image/Copilot-api.exe
        retention-days: 5

    - name: Upload Linux Build
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: target/native-image/Copilot-api
        retention-days: 5

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/Copilot-api.jar
          target/native-image/Copilot-api
          target/native-image/Copilot-api.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
