name: AOT Compile and Release

on:
  push:
    branches:
      - main
    paths:
      - 'Spring/**'
      - '.github/workflows/Spring.yml'

jobs:
  build:
    name: Build for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            mvnw_cmd: ".\\mvnw.cmd"
          - os: ubuntu-latest
            arch: amd64
            mvnw_cmd: "./mvnw"
          - os: ubuntu-latest
            arch: arm64
            mvnw_cmd: "./mvnw"
          - os: macos-latest
            arch: amd64
            mvnw_cmd: "./mvnw"
          - os: macos-latest
            arch: arm64
            mvnw_cmd: "./mvnw"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          architecture: ${{ matrix.arch }}

      - name: Make mvnw Executable (Non-Windows)
        if: runner.os != 'Windows'
        run: chmod +x Spring/mvnw

      - name: Run AOT Compilation
        working-directory: Spring
        run: ${{ matrix.mvnw_cmd }} native:compile -Pnative -DskipTests

      - name: Package Application
        working-directory: Spring
        run: ${{ matrix.mvnw_cmd }} package -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # artifact 名称中包含平台和架构信息
          name: Copilot-API-Spring-${{ matrix.os }}-${{ matrix.arch }}
          path: Spring/target

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # 筛选出只保留需要的 6 个文件（完全匹配文件名），其他文件均跳过
      - name: Filter Release Assets
        run: |
          mkdir -p release-artifacts
          for file in $(find artifacts -type f); do
            base=$(basename "$file")
            case "$base" in
              CopilotSpringNative-0.0.1-SNAPSHOT.jar)
                cp "$file" release-artifacts/"$base"
                ;;
              CopilotSpringNative-Copilot-API-Spring-macos-latest-amd64)
                cp "$file" release-artifacts/"$base"
                ;;
              CopilotSpringNative-Copilot-API-Spring-macos-latest-arm64)
                cp "$file" release-artifacts/"$base"
                ;;
              CopilotSpringNative-Copilot-API-Spring-ubuntu-latest-amd64)
                cp "$file" release-artifacts/"$base"
                ;;
              CopilotSpringNative-Copilot-API-Spring-ubuntu-latest-arm64)
                cp "$file" release-artifacts/"$base"
                ;;
              CopilotSpringNative-Copilot-API-Spring-windows-latest-amd64.exe)
                cp "$file" release-artifacts/"$base"
                ;;
              *)
                echo "Skipping $base"
                ;;
            esac
          done
          echo "Filtered files:"
          ls -l release-artifacts

      - name: Create version
        id: version
        run: |
          # 生成 tag 格式为 YYYY-MM-DD，例如：2025-03-06
          VERSION=$(date +%Y-%m-%d)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: release-artifacts/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 可选：将 artifacts 同步到 artifacts 分支
      - name: Check for artifacts branch
        id: check_branch
        run: |
          git fetch origin
          if git ls-remote --heads origin artifacts | grep artifacts > /dev/null; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create artifacts branch if needed
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: |
          git checkout -b artifacts
          mkdir -p spring
          touch spring/.gitkeep
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Initialize artifacts branch"
          git push -u origin artifacts

      - name: Checkout artifacts branch
        uses: actions/checkout@v4
        with:
          ref: artifacts
          fetch-depth: 0
          path: artifacts-branch

      - name: Update artifacts branch
        run: |
          mkdir -p artifacts-branch/spring
          cp -r release-artifacts/* artifacts-branch/spring/ || echo "No Spring artifacts to copy"
          cd artifacts-branch
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update artifacts for ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin artifacts
