name: AOT Compile and Release

on:
  push:
    branches:
      - main
    paths:
      - 'Spring/**'
      - '.github/workflows/Spring.yml'

jobs:
  build:
    name: Build for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            mvnw_cmd: ".\\mvnw.cmd"
          - os: ubuntu-latest
            arch: amd64
            mvnw_cmd: "./mvnw"
          - os: ubuntu-latest
            arch: arm64
            mvnw_cmd: "./mvnw"
          - os: macos-latest
            arch: amd64
            mvnw_cmd: "./mvnw"
          - os: macos-latest
            arch: arm64
            mvnw_cmd: "./mvnw"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          architecture: ${{ matrix.arch }}

      - name: Make mvnw Executable (Non-Windows)
        if: runner.os != 'Windows'
        run: chmod +x Spring/mvnw

      - name: Run AOT Compilation
        working-directory: Spring
        run: ${{ matrix.mvnw_cmd }} native:compile -Pnative -DskipTests

      - name: Package Application
        working-directory: Spring
        run: ${{ matrix.mvnw_cmd }} package -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # 上传的 artifact 名称中包含平台和架构信息
          name: Copilot-API-Spring-${{ matrix.os }}-${{ matrix.arch }}
          path: Spring/target

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # 筛选出只上传以 CopilotSpringNative 开头的文件，并排除 .class 和 .json 文件，同时根据 artifact 目录重命名文件
      - name: Filter and Rename Release Assets
        run: |
          mkdir -p release-artifacts
          # 查找所有以 CopilotSpringNative 开头、排除 .json 和 .class 后缀的文件
          find artifacts -type f -name 'CopilotSpringNative*' ! -name '*.json' ! -name '*.class' | while read file; do
            # 获取所在 artifact 目录名称，例如 "Copilot-API-Spring-ubuntu-latest-amd64"
            parent_dir=$(basename "$(dirname "$file")")
            # 原始文件名
            base=$(basename "$file")
            # 如果有扩展名，分离名称和扩展名
            if [[ "$base" == *.* ]]; then
              name_noext="${base%.*}"
              ext="${base##*.}"
            else
              name_noext="$base"
              ext=""
            fi
            # 拼接新文件名，格式为：<原始名称>-<artifact目录>.[ext]
            newname="${name_noext}-${parent_dir}"
            if [ -n "$ext" ]; then
              newname="${newname}.${ext}"
            fi
            cp "$file" "release-artifacts/$newname"
          done
          echo "Filtered and renamed files:"
          ls -l release-artifacts

      - name: Create version
        id: version
        run: |
          VERSION=$(date +v-%y-%m-%d)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: release-artifacts/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 可选：将 artifacts 同步到 artifacts 分支（根据需要）
      - name: Check for artifacts branch
        id: check_branch
        run: |
          git fetch origin
          if git ls-remote --heads origin artifacts | grep artifacts > /dev/null; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
      - name: Create artifacts branch if needed
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: |
          git checkout -b artifacts
          mkdir -p spring
          touch spring/.gitkeep
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Initialize artifacts branch"
          git push -u origin artifacts
      - name: Checkout artifacts branch
        uses: actions/checkout@v4
        with:
          ref: artifacts
          fetch-depth: 0
          path: artifacts-branch
      - name: Update artifacts branch
        run: |
          mkdir -p artifacts-branch/spring
          cp -r release-artifacts/* artifacts-branch/spring/ || echo "No Spring artifacts to copy"
          cd artifacts-branch
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update artifacts for ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin artifacts
